### ISSUE TITLE
TODO for audio.getBroadcastList API

### ISSUE THREAD

**Issue by kstep** [kstep/vkrs#53]
- [ ] join up `GetFriendsBroadcastList` and `GetGroupsBroadcastList` into a single `GetBroadcastList` request
- [ ] iimprove `User` model (see #3)
- [ ] improve `Group` model (see #13)
